// import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';
import { Providers } from '@/Providers';
import { Metadata, Viewport } from 'next';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  // Also supported by less commonly used
  // interactiveWidget: 'resizes-visual',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    // suppressHydrationWarning - для отключении проверки гидратации для тега HTML
    <html lang='en' suppressHydrationWarning={true}>
      {/*<head>*/}
      {/*  <meta name='viewport' content='initial-scale=1, width=device-width' />*/}
      {/*</head>*/}
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
